config/routes.rb
App::Application.routes.draw do
  resources :users

  root 'users#home'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'
 	get 'auth/failure', to: redirect('/')

end

app/models/movie.rb
class Movie <ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :movies

  after_create :fetch_movie_history
# need a better find_or_create method
  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]      	
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
      user.image = auth["info"]["image"]
      user.first_name = auth["info"]["first_name"]
      user.token = auth["credentials"]["token"]
      user.refresh_token = auth["credentials"]["refresh_token"]
      user.expires_at = auth["credentials"]["expires_at"]
    end
   end

  def youtube_client    
    YouTubeIt::OAuth2Client.new(
      client_access_token: token, 
      client_id: ENV['CLIENT_ID'], 
      client_secret: ENV['CLIENT_SECRET'], 
      dev_key: ENV['DEV_KEY'],
      client_refresh_token: refresh_token,
      client_token_expires_at: expires_at)
  end

  def fetch_movie_history
    #self.youtube_client.refresh_access_token!
    watch_history = self.youtube_client.watch_history
    watch_history.videos.each do |video|
      movie = Movie.find_or_create_by(unique_id: video.unique_id)
      movie.title = video.title
      movie.description = video.description
      movie.url = video.player_url
      movie.thumbnail = video.thumbnails[3].url
      movie.save
      self.movies << movie
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def create
	  user = User.from_omniauth(env["omniauth.auth"])
	  session[:user_id] = user.id
	  redirect_to users_url, notice: "Signed in!"
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, notice: "Signed out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "me & you tube" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="fixed">
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "me & you tube", root_path %></a></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
            <% if current_user %>
              <li><%= link_to "Sign out", signout_path %><li>
            <% end %>
          <li class="divider"></li>
          <li class="has-form">
            <a href="https://twitter.com/intent/tweet?screen_name=plainpioneer&text=Let's%20me%20%26%20you%20watch%20" class="button" data-related="plainpioneer">Tweet to @plainpioneer</a>
              <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
          </li>
        </ul>
      </section>
    </nav>
  </div>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/users/home.html.erb
<div class="row">
	<div class="large-12 small-centered columns">
		<br>
		<br>
		<h1>Watched anything good lately?</h1>
		<br>
		<br>
	</div>
</div>
<div class="row">
	<div class="large-12 small-centered columns">
		<br>
		<br>
		<a href="<%="/auth/google_oauth2" %>" class="large button expand">Sign in with YouTube</a>
		<br>
		<br>
	</div>
</div>

app/views/users/index.html.erb
<!-- <div class="row">
	<div class="large-12 columns">
	  		<#% @users.each do |user| %>
					<div class="row"><h3> <#%= user.name %></h3></div>
					<div class="row"><#%= image_tag user.image %></div>
				<#% end %>
	</div>
</div> -->

<div class="row">
	<div class="large-12 columns">
		<br>
		<br>
		<h1>What should we watch together?</h1>
		<br>
		<br>
	</div>
</div>


<div class="row">
	<% @users.each do |user| %>
	 	<% user.movies.each do |movie| %>
		<div class="small-6 columns">
				<div class="flex-video">
					<iframe 
						id="ytplayer" 
						type="text/html" 
						width="640" 
						height="390" 
						src="https://www.youtube.com/embed/<%= movie.unique_id %>" 
						frameborder="0" 
						controls="2" />
						</iframe>
				</div>
		</div>
		<% end %>
	<% end %>
</div>